"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.mockupPreviewPlugin = mockupPreviewPlugin;
var fs_1 = require("fs");
var path_1 = require("path");
var fast_glob_1 = require("fast-glob");
var chokidar_1 = require("chokidar");
var MOCKUPS_DIR = "src/components/mockups";
var GENERATED_MODULE = "src/.generated/mockup-components.ts";
function mockupPreviewPlugin() {
    var root = "";
    var currentSource = "";
    var watcher = null;
    function getMockupsAbsDir() {
        return path_1.default.join(root, MOCKUPS_DIR);
    }
    function getGeneratedModuleAbsPath() {
        return path_1.default.join(root, GENERATED_MODULE);
    }
    function isMockupFile(absolutePath) {
        var rel = path_1.default.relative(getMockupsAbsDir(), absolutePath);
        return (!rel.startsWith("..") && !path_1.default.isAbsolute(rel) && rel.endsWith(".tsx"));
    }
    function isPreviewTarget(relativeToMockups) {
        return relativeToMockups
            .split(path_1.default.sep)
            .every(function (segment) { return !segment.startsWith("_"); });
    }
    function discoverComponents() {
        return __awaiter(this, void 0, void 0, function () {
            var files;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, (0, fast_glob_1.default)("".concat(MOCKUPS_DIR, "/**/*.tsx"), {
                            cwd: root,
                            ignore: ["**/_*/**", "**/_*.tsx"],
                        })];
                    case 1:
                        files = _a.sent();
                        return [2 /*return*/, files.map(function (f) { return ({
                                globKey: "./" + f.slice("src/".length),
                                importPath: path_1.default.posix.relative("src/.generated", f),
                            }); })];
                }
            });
        });
    }
    function generateSource(components) {
        var entries = components
            .map(function (c) {
            return "  ".concat(JSON.stringify(c.globKey), ": () => import(").concat(JSON.stringify(c.importPath), ")");
        })
            .join(",\n");
        return [
            "// This file is auto-generated by mockupPreviewPlugin.ts.",
            "type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;",
            "export const modules: ModuleMap = {",
            entries,
            "};",
            "",
        ].join("\n");
    }
    function shouldAutoRescan(pathname) {
        return (pathname.includes("/components/mockups/") ||
            pathname.includes("/.generated/mockup-components"));
    }
    var refreshInFlight = false;
    var refreshQueued = false;
    function refresh() {
        return __awaiter(this, void 0, void 0, function () {
            var changed, components, newSource, generatedModuleAbsPath, followUp;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        if (refreshInFlight) {
                            refreshQueued = true;
                            return [2 /*return*/, false];
                        }
                        refreshInFlight = true;
                        changed = false;
                        _a.label = 1;
                    case 1:
                        _a.trys.push([1, , 3, 4]);
                        return [4 /*yield*/, discoverComponents()];
                    case 2:
                        components = _a.sent();
                        newSource = generateSource(components);
                        if (newSource !== currentSource) {
                            currentSource = newSource;
                            generatedModuleAbsPath = getGeneratedModuleAbsPath();
                            (0, fs_1.mkdirSync)(path_1.default.dirname(generatedModuleAbsPath), { recursive: true });
                            (0, fs_1.writeFileSync)(generatedModuleAbsPath, currentSource);
                            changed = true;
                        }
                        return [3 /*break*/, 4];
                    case 3:
                        refreshInFlight = false;
                        return [7 /*endfinally*/];
                    case 4:
                        if (!refreshQueued) return [3 /*break*/, 6];
                        refreshQueued = false;
                        return [4 /*yield*/, refresh()];
                    case 5:
                        followUp = _a.sent();
                        return [2 /*return*/, changed || followUp];
                    case 6: return [2 /*return*/, changed];
                }
            });
        });
    }
    function onFileAddedOrRemoved() {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, refresh()];
                    case 1:
                        _a.sent();
                        return [2 /*return*/];
                }
            });
        });
    }
    return {
        name: "mockup-preview",
        enforce: "pre",
        configResolved: function (config) {
            root = config.root;
        },
        buildStart: function () {
            return __awaiter(this, void 0, void 0, function () {
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, refresh()];
                        case 1:
                            _a.sent();
                            return [2 /*return*/];
                    }
                });
            });
        },
        configureServer: function (viteServer) {
            return __awaiter(this, void 0, void 0, function () {
                var mockupsAbsDir;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, refresh()];
                        case 1:
                            _a.sent();
                            mockupsAbsDir = getMockupsAbsDir();
                            (0, fs_1.mkdirSync)(mockupsAbsDir, { recursive: true });
                            watcher = chokidar_1.default.watch(mockupsAbsDir, {
                                ignoreInitial: true,
                                awaitWriteFinish: {
                                    stabilityThreshold: 100,
                                    pollInterval: 50,
                                },
                            });
                            watcher.on("add", function (file) {
                                if (isMockupFile(file) &&
                                    isPreviewTarget(path_1.default.relative(mockupsAbsDir, file))) {
                                    void onFileAddedOrRemoved();
                                }
                            });
                            watcher.on("unlink", function (file) {
                                if (isMockupFile(file)) {
                                    void onFileAddedOrRemoved();
                                }
                            });
                            viteServer.middlewares.use(function (req, res, next) {
                                var _a;
                                var requestUrl = new URL((_a = req.url) !== null && _a !== void 0 ? _a : "/", "http://127.0.0.1");
                                var pathname = requestUrl.pathname;
                                var originalEnd = res.end.bind(res);
                                res.end = (function () {
                                    var args = [];
                                    for (var _i = 0; _i < arguments.length; _i++) {
                                        args[_i] = arguments[_i];
                                    }
                                    if (res.statusCode === 404 && shouldAutoRescan(pathname)) {
                                        void refresh();
                                    }
                                    return originalEnd.apply(void 0, args);
                                });
                                next();
                            });
                            return [2 /*return*/];
                    }
                });
            });
        },
        closeWatcher: function () {
            return __awaiter(this, void 0, void 0, function () {
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0:
                            if (!watcher) return [3 /*break*/, 2];
                            return [4 /*yield*/, watcher.close()];
                        case 1:
                            _a.sent();
                            _a.label = 2;
                        case 2: return [2 /*return*/];
                    }
                });
            });
        },
    };
}
