import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

export type Language = "en" | "hi" | "mr";

export interface LanguageOption {
  code: Language;
  label: string;
  nativeLabel: string;
}

export const languageOptions: LanguageOption[] = [
  { code: "en", label: "English", nativeLabel: "English" },
  { code: "hi", label: "Hindi", nativeLabel: "हिन्दी" },
  { code: "mr", label: "Marathi", nativeLabel: "मराठी" },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    citizen: "Citizen",
    nagarsevak: "Nagarsevak",
    headAdmin: "Head Admin",
    reportProblem: "Report a Problem",
    reportProblemSub: "Click photo → Ward officer resolves it",
    active: "Active",
    resolved: "Resolved",
    community: "Community",
    feed: "Feed",
    panel: "Panel",
    admin: "Admin",
    officer: "Officer",
    alertsAndNews: "Alerts & News",
    live: "LIVE",
    recentComplaints: "Recent Complaints",
    viewAll: "View All",
    tapToReport: "Tap to report your first problem",
    utilityStatus: "Utility Status",
    quickServices: "Quick Services",
    allServices: "All Services",
    emergencyContacts: "Emergency Contacts",
    waterSupply: "Water Supply",
    electricity: "Electricity",
    hospitals: "Hospitals",
    childCare: "Child Care",
    clinics: "Clinics",
    police: "Police",
    banks: "Banks",
    postOffice: "Post Office",
    schools: "Schools",
    crematorium: "Crematorium",
    nearbyServices: "Nearby Services",
    ulhasnagar: "Ulhasnagar",
    complaints: "Complaints",
    newComplaint: "New Complaint",
    myComplaints: "My Complaints",
    communityFeed: "Community Feed",
    profile: "Profile",
    emergency: "Emergency",
    sos: "SOS",
    home: "Home",
    welcome: "Welcome",
    enterMobile: "Enter your mobile number to login or register",
    continue: "Continue",
    selectRole: "Select Your Role",
    selectRoleSub: "How would you like to use JanSeva?",
    completeProfile: "Complete Your Profile",
    fullName: "Full Name",
    age: "Age",
    email: "Email",
    wardLocation: "Ward / Location",
    selectWard: "Select your ward",
    register: "Register & Continue",
    required: "Required",
    optional: "Optional",
    welcomeBack: "Welcome back!",
    loginAs: "Login as",
    differentNumber: "Use different number",
    logout: "Logout",
    logoutConfirm: "Are you sure you want to logout from JanSeva?",
    cancel: "Cancel",
    yesLogout: "Yes, Logout",
    quickActions: "QUICK ACTIONS",
    viewTrackComplaints: "View and track all complaints",
    clickPhotoRaise: "Click a photo and raise complaint",
    wardUpdates: "Ward updates & announcements",
    quickAccessHelp: "Quick access to help numbers",
    accountDetails: "ACCOUNT DETAILS",
    usefulLinks: "USEFUL LINKS",
    loginSignUp: "Login / Sign Up",
    loginToAccess: "Login to access your profile",
    welcomeToJanSeva: "Welcome to JanSeva",
    language: "Language",
    changeLanguage: "Change Language",
    selectLanguage: "Select Language",
    poweredBy: "Powered by Vanchit Bahujan Aaghadi",
    citizenPlatform: "Citizen Services Platform",
    getStarted: "Get Started",
    tapToContinue: "Tap to continue",
    alert: "Alert",
    news: "News",
    bedAvailability: "Bed Availability",
    totalBeds: "Total Beds",
    occupied: "Occupied",
    available: "Available",
    servicesProvided: "Services Provided",
    contactNumbers: "Contact Numbers",
    recentReviews: "Recent Reviews",
    reviews: "reviews",
    call: "Call",
    moreContacts: "more contacts — Tap to view all details",
    bedsFree: "beds free",
    hoursDay: "Hours/day",
    reduced: "Reduced",
    normal: "Normal",
    submitted: "Submitted",
    assigned: "Assigned",
    inProgress: "In Progress",
    rejected: "Rejected",
    fullNameReq: "Full Name",
    mobile: "Mobile",
    ward: "Ward",
    role: "Role",
    total: "Total",
    goBack: "Go Back",
    placeNotFound: "Place not found",
    nagarsevakPanel: "Nagarsevak Panel",
    headAdminPanel: "Head Admin Panel",
    manageAllWards: "Manage all wards, services & officers",
    viewResolveWard: "View & resolve ward complaints",
    reportProblemAction: "Report Problem",
  },
  hi: {
    goodMorning: "सुप्रभात",
    goodAfternoon: "नमस्कार",
    goodEvening: "शुभ संध्या",
    citizen: "नागरिक",
    nagarsevak: "नगरसेवक",
    headAdmin: "मुख्य प्रशासक",
    reportProblem: "समस्या दर्ज करें",
    reportProblemSub: "फोटो क्लिक करें → वार्ड अधिकारी हल करेंगे",
    active: "सक्रिय",
    resolved: "हल किया",
    community: "समुदाय",
    feed: "फ़ीड",
    panel: "पैनल",
    admin: "प्रशासक",
    officer: "अधिकारी",
    alertsAndNews: "सूचनाएं और समाचार",
    live: "लाइव",
    recentComplaints: "हाल की शिकायतें",
    viewAll: "सभी देखें",
    tapToReport: "अपनी पहली समस्या दर्ज करने के लिए टैप करें",
    utilityStatus: "सेवा स्थिति",
    quickServices: "त्वरित सेवाएं",
    allServices: "सभी सेवाएं",
    emergencyContacts: "आपातकालीन संपर्क",
    waterSupply: "जल आपूर्ति",
    electricity: "बिजली",
    hospitals: "अस्पताल",
    childCare: "बाल चिकित्सा",
    clinics: "क्लिनिक",
    police: "पुलिस",
    banks: "बैंक",
    postOffice: "डाकघर",
    schools: "विद्यालय",
    crematorium: "शमशानभूमि",
    nearbyServices: "नजदीकी सेवाएं",
    ulhasnagar: "उल्हासनगर",
    complaints: "शिकायतें",
    newComplaint: "नई शिकायत",
    myComplaints: "मेरी शिकायतें",
    communityFeed: "समुदाय फ़ीड",
    profile: "प्रोफ़ाइल",
    emergency: "आपातकालीन",
    sos: "एसओएस",
    home: "होम",
    welcome: "स्वागत है",
    enterMobile: "लॉगिन या रजिस्टर करने के लिए अपना मोबाइल नंबर दर्ज करें",
    continue: "जारी रखें",
    selectRole: "अपनी भूमिका चुनें",
    selectRoleSub: "आप JanSeva का उपयोग कैसे करना चाहते हैं?",
    completeProfile: "अपनी प्रोफ़ाइल पूरी करें",
    fullName: "पूरा नाम",
    age: "उम्र",
    email: "ईमेल",
    wardLocation: "वार्ड / स्थान",
    selectWard: "अपना वार्ड चुनें",
    register: "रजिस्टर करें और जारी रखें",
    required: "आवश्यक",
    optional: "वैकल्पिक",
    welcomeBack: "वापसी पर स्वागत है!",
    loginAs: "लॉगिन करें",
    differentNumber: "अलग नंबर उपयोग करें",
    logout: "लॉगआउट",
    logoutConfirm: "क्या आप JanSeva से लॉगआउट करना चाहते हैं?",
    cancel: "रद्द करें",
    yesLogout: "हां, लॉगआउट",
    quickActions: "त्वरित कार्य",
    viewTrackComplaints: "सभी शिकायतें देखें और ट्रैक करें",
    clickPhotoRaise: "फोटो क्लिक करें और शिकायत दर्ज करें",
    wardUpdates: "वार्ड अपडेट और घोषणाएं",
    quickAccessHelp: "सहायता नंबर तक तेज़ पहुंच",
    accountDetails: "खाता विवरण",
    usefulLinks: "उपयोगी लिंक",
    loginSignUp: "लॉगिन / साइन अप",
    loginToAccess: "प्रोफ़ाइल एक्सेस करने के लिए लॉगिन करें",
    welcomeToJanSeva: "JanSeva में स्वागत है",
    language: "भाषा",
    changeLanguage: "भाषा बदलें",
    selectLanguage: "भाषा चुनें",
    poweredBy: "Powered by वंचित बहुजन आघाडी",
    citizenPlatform: "नागरिक सेवा मंच",
    getStarted: "शुरू करें",
    tapToContinue: "जारी रखने के लिए टैप करें",
    alert: "सूचना",
    news: "समाचार",
    bedAvailability: "बेड उपलब्धता",
    totalBeds: "कुल बेड",
    occupied: "भरे हुए",
    available: "उपलब्ध",
    servicesProvided: "उपलब्ध सेवाएं",
    contactNumbers: "संपर्क नंबर",
    recentReviews: "हाल की समीक्षाएं",
    reviews: "समीक्षाएं",
    call: "कॉल",
    moreContacts: "और संपर्क — सभी विवरण देखने के लिए टैप करें",
    bedsFree: "बेड उपलब्ध",
    hoursDay: "घंटे/दिन",
    reduced: "कम",
    normal: "सामान्य",
    submitted: "जमा किया",
    assigned: "सौंपा गया",
    inProgress: "प्रगति में",
    rejected: "अस्वीकृत",
    fullNameReq: "पूरा नाम",
    mobile: "मोबाइल",
    ward: "वार्ड",
    role: "भूमिका",
    total: "कुल",
    goBack: "वापस जाएं",
    placeNotFound: "स्थान नहीं मिला",
    nagarsevakPanel: "नगरसेवक पैनल",
    headAdminPanel: "मुख्य प्रशासक पैनल",
    manageAllWards: "सभी वार्ड, सेवाएं और अधिकारी प्रबंधित करें",
    viewResolveWard: "वार्ड शिकायतें देखें और हल करें",
    reportProblemAction: "समस्या दर्ज करें",
  },
  mr: {
    goodMorning: "सुप्रभात",
    goodAfternoon: "नमस्कार",
    goodEvening: "शुभ संध्याकाळ",
    citizen: "नागरिक",
    nagarsevak: "नगरसेवक",
    headAdmin: "मुख्य प्रशासक",
    reportProblem: "समस्या नोंदवा",
    reportProblemSub: "फोटो काढा → वॉर्ड अधिकारी सोडवतील",
    active: "सक्रिय",
    resolved: "सोडवले",
    community: "समुदाय",
    feed: "फीड",
    panel: "पॅनेल",
    admin: "प्रशासक",
    officer: "अधिकारी",
    alertsAndNews: "सूचना आणि बातम्या",
    live: "लाइव्ह",
    recentComplaints: "अलीकडील तक्रारी",
    viewAll: "सर्व पहा",
    tapToReport: "तुमची पहिली समस्या नोंदवण्यासाठी टॅप करा",
    utilityStatus: "सेवा स्थिती",
    quickServices: "जलद सेवा",
    allServices: "सर्व सेवा",
    emergencyContacts: "आणीबाणी संपर्क",
    waterSupply: "पाणीपुरवठा",
    electricity: "वीज",
    hospitals: "रुग्णालये",
    childCare: "बालरोग",
    clinics: "दवाखाने",
    police: "पोलीस",
    banks: "बँका",
    postOffice: "टपालघर",
    schools: "शाळा",
    crematorium: "शमशानभूमी",
    nearbyServices: "जवळपासच्या सेवा",
    ulhasnagar: "उल्हासनगर",
    complaints: "तक्रारी",
    newComplaint: "नवीन तक्रार",
    myComplaints: "माझ्या तक्रारी",
    communityFeed: "समुदाय फीड",
    profile: "प्रोफाइल",
    emergency: "आणीबाणी",
    sos: "एसओएस",
    home: "होम",
    welcome: "स्वागत",
    enterMobile: "लॉगिन किंवा नोंदणी करण्यासाठी तुमचा मोबाइल नंबर टाका",
    continue: "पुढे जा",
    selectRole: "तुमची भूमिका निवडा",
    selectRoleSub: "तुम्हाला JanSeva कसे वापरायचे आहे?",
    completeProfile: "तुमचे प्रोफाइल पूर्ण करा",
    fullName: "पूर्ण नाव",
    age: "वय",
    email: "ईमेल",
    wardLocation: "वॉर्ड / ठिकाण",
    selectWard: "तुमचा वॉर्ड निवडा",
    register: "नोंदणी करा आणि पुढे जा",
    required: "आवश्यक",
    optional: "ऐच्छिक",
    welcomeBack: "पुन्हा स्वागत!",
    loginAs: "म्हणून लॉगिन करा",
    differentNumber: "वेगळा नंबर वापरा",
    logout: "लॉगआउट",
    logoutConfirm: "तुम्हाला JanSeva मधून लॉगआउट करायचे आहे का?",
    cancel: "रद्द करा",
    yesLogout: "हो, लॉगआउट",
    quickActions: "जलद कार्ये",
    viewTrackComplaints: "सर्व तक्रारी पहा आणि ट्रॅक करा",
    clickPhotoRaise: "फोटो काढा आणि तक्रार नोंदवा",
    wardUpdates: "वॉर्ड अपडेट आणि घोषणा",
    quickAccessHelp: "मदत क्रमांकांना जलद प्रवेश",
    accountDetails: "खाते तपशील",
    usefulLinks: "उपयुक्त लिंक",
    loginSignUp: "लॉगिन / साइन अप",
    loginToAccess: "प्रोफाइल पाहण्यासाठी लॉगिन करा",
    welcomeToJanSeva: "JanSeva मध्ये स्वागत",
    language: "भाषा",
    changeLanguage: "भाषा बदला",
    selectLanguage: "भाषा निवडा",
    poweredBy: "Powered by वंचित बहुजन आघाडी",
    citizenPlatform: "नागरिक सेवा व्यासपीठ",
    getStarted: "सुरू करा",
    tapToContinue: "पुढे जाण्यासाठी टॅप करा",
    alert: "सूचना",
    news: "बातमी",
    bedAvailability: "बेड उपलब्धता",
    totalBeds: "एकूण बेड",
    occupied: "भरलेले",
    available: "उपलब्ध",
    servicesProvided: "उपलब्ध सेवा",
    contactNumbers: "संपर्क क्रमांक",
    recentReviews: "अलीकडील पुनरावलोकने",
    reviews: "पुनरावलोकने",
    call: "कॉल",
    moreContacts: "आणखी संपर्क — सर्व तपशील पाहण्यासाठी टॅप करा",
    bedsFree: "बेड उपलब्ध",
    hoursDay: "तास/दिवस",
    reduced: "कमी",
    normal: "सामान्य",
    submitted: "सबमिट केले",
    assigned: "नियुक्त",
    inProgress: "प्रगतीत",
    rejected: "नाकारले",
    fullNameReq: "पूर्ण नाव",
    mobile: "मोबाइल",
    ward: "वॉर्ड",
    role: "भूमिका",
    total: "एकूण",
    goBack: "मागे जा",
    placeNotFound: "ठिकाण सापडले नाही",
    nagarsevakPanel: "नगरसेवक पॅनेल",
    headAdminPanel: "मुख्य प्रशासक पॅनेल",
    manageAllWards: "सर्व वॉर्ड, सेवा आणि अधिकारी व्यवस्थापित करा",
    viewResolveWard: "वॉर्ड तक्रारी पहा आणि सोडवा",
    reportProblemAction: "समस्या नोंदवा",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
}

const LANG_KEY = "janseva_language";

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLang] = useState<Language>("en");

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then((stored) => {
      if (stored && (stored === "en" || stored === "hi" || stored === "mr")) {
        setLang(stored as Language);
      }
    });
  }, []);

  const setLanguage = async (lang: Language) => {
    setLang(lang);
    await AsyncStorage.setItem(LANG_KEY, lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations.en[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be inside LanguageProvider");
  return ctx;
}
